--- #YAML:1.0
name:               Net-Rackspace-Notes
version:            0.0001
abstract:           A way to interface with your Rackspace Email Notes.
author:
    - Naveed Massjouni <naveedm9@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::General:   0
    JSON:              0
    LWP::UserAgent:    0
    MooseX::Declare:   0
    MooseX::NonMoose:  0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
