--- #YAML:1.0
name:               Net-Rackspace-Notes
version:            0.0200
abstract:           A way to interface with your Rackspace Email Notes.
author:
    - Naveed Massjouni <naveedm9@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::Rad:             1.04
    JSON:                 2.22
    LWP::UserAgent:       5.835
    Moose:                1.12
    Parallel::ForkManager:  0.7.6
    Term::ReadPassword:   0.11
resources:
    bugtracker:  http://github.com/ironcamel/Net-Rackspace-Notes/issues
    repository:  http://github.com/ironcamel/Net-Rackspace-Notes
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
