---
abstract: 'An interface to Rackspace Email Notes.'
author:
  - 'Naveed Massjouni <naveedm9@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Rackspace-Notes
requires:
  App::Rad: 1.04
  HTTP::Request: 0
  JSON: 2.22
  LWP::UserAgent: 5.835
  Moose: 1.12
  Parallel::ForkManager: 0.7.6
  Term::ReadPassword: 0.11
resources:
  bugtracker: http://github.com/ironcamel/Net-Rackspace-Notes/issues
  repository: git://github.com/ironcamel/Net-Rackspace-Notes
version: 1.0000
